name: KuffleItems
version: 1.0
author: KosmosUniverse
main: fr.kosmosuniverse.kuffleitems.KuffleMain
api-version: 1.15

commands:
   ki-config:
      usage: /<command>
      description: command to see or change game configuration
      permission: inferno.flagrate
   ki-list:
      usage: /<command> [reset | remove <Player name> | add <@a | Player name>]
      description: command to add/remove players to the list and view/reset the list
      permission: inferno.flagrate
   ki-start:
      usage: /<command>
      description: command to start the game
      permission: inferno.flagrate
   ki-stop:
      usage: /<command>
      description: command to stop the game when it is running
      permission: inferno.flagrate
   ki-team-create:
      usage: /<command> <TeamName> [TeamColor]
      description: command to create Team
      permission: inferno.flagrate
   ki-team-delete:
      usage: /<command> <TeamName>
      description: command to delete Team
      permission: inferno.flagrate
   ki-team-affect-player:
      usage: /<command> <TeamName> <PlayerName>
      description: command to affect a Player to a Team
      permission: inferno.flagrate
   ki-team-remove-player:
      usage: /<command> <TeamName> <PlayerName>
      description: command to remove a Player from a Team
      permission: inferno.flagrate
   ki-team-reset-players:
      usage: /<command> <TeamName>
      description: command to reset player list in a team
      permission: inferno.flagrate
   ki-team-random-player:
      usage: /<command>
      description: command to put random players in teams
      permission: inferno.flagrate
   ki-team-show:
      usage: /<command> [TeamName]
      description: command to show all or one team
      permission: inferno.flagrate
   ki-team-color:
      usage: /<command> <TeamName> <TeamColor>
      description: command to change team color
      permission: inferno.flagrate

permissions:
   ki-config:
      default: op
      description: command to see or change game configuration
   ki-list:
      description: command to add players to the list and view the list
      default: op
   ki-start:
      description: command to start the game
      default: op
   ki-stop:
      description: command to stop the game when it is running
      default: op
   ki-team-create:
      description: command to create Team
      default: op
   ki-team-delete:
      description: command to delete Team
      default: op
   ki-team-affect-player:
      description: command to affect a Player to a Team
      default: op
   ki-team-remove-player:
      description: command to remove a Player from a Team
      default: op
   ki-team-reset-players:
      description: command to reset player list in a team
      default: op
   ki-team-random-player:
      description: command to put random players in teams
      default: op
   ki-team-show:
      description: command to show all or one team
      default: op
   ki-team-color:
      description: command to change team color
      default: op